### ISSUE TITLE
Issue with Item Stacking after installing the mod

### ISSUE THREAD

**Issue by Pranavk246** [BradBot1/FabricSit#10]
Hello, thank you for making this awesome mod. I love everything about it but can’t help but wonder why this glitch is occurring after installing the mod on my server. Randomly some items become impossible to stack once obtained and the only way to make it work again is to throw all the similar items on the floor and make it stack on the floor and then pickup. 

I started facing this issue only after installing this mod and have tested without it installed and things seem to work again.

The mods I have installed on my server are - 
1. Lithium - 0.7.3
2. Fabric Tailor - 1.6.3
3. Fabric API - 0.38.2
4. Fabric Sit - 1.6.1
5. BFAPI - v1.1.9

Server MC version - 1.17.1 

Please let me know if you need any more details to help resolve this issue!

**Comment by Pranavk246** [comment]
Sorry I forgot to add that this issue occurs when you place something on the floor, break it and then pick it up. It starts stacking separately from the original stack. I have tried removing all mods and just adding this mod and this issue only persists when I use this mod.

**Comment by BradBot1** [comment]
I will have a look now, thanks for reporting this

**Comment by BradBot1** [comment]
i accidently closed this whoops

**Comment by BradBot1** [comment]
I have found the issue, the mark provider creates an nbt tag if one is not present without checking if it should. Then the item it created the tag on is different to the originals. 

This will be patched next version, for now please downgrade to 1.1.8

If this issue continues please reopen this issue

**Comment by Pranavk246** [comment]
Thank you so much for your prompt response. I will downgrade like you suggested and if I face the same issue I will get back to you. 

Cheers! :)
