### ISSUE TITLE
Ability to sit on slabs and stairs while holding items

### ISSUE THREAD

**Issue by Pranavk246** [BradBot1/FabricSit#11]
Its a small enhancement but will help a lot if you can make it so that we can sit on slabs and stairs using right click option while holding any item. Currently it needs to be an empty hand for me to be able to sit. 

The functionality would be similar to boats once implemented! :)

**Comment by BradBot1** [comment]
This is intentional behaviour, if there was no check players may unintentionally sit.

I could make this configurable if that is what you would like; however, with default settings this behaviour will not change.

**Comment by Pranavk246** [comment]
Ok that makes sense and thinking about it I can see why this would be a bad idea. However having a toggle to be able to turn on and off would definitely be a cool touch if its not too much of a hassle to do! :)

**Comment by BradBot1** [comment]
Done, update to 1.6.2 to get the new config option.

**Comment by Pranavk246** [comment]
Thanks a ton for this option. I appreciate all the support you have given to this mod so far. Sorry if this is off topic but say I wanna use this mod on my single player world, is it not possible? 

If it is possible what steps do I have to take to make this work? 

EDIT: Spellings

**Comment by BradBot1** [comment]
Hey, It should work on a singleplayer world by hooking onto your internal server instance, if it doesnt work and crashes send your crash logs and i would be more then happy to help fix it for you.

**Comment by BradBot1** [comment]
Hey, It should work on a singleplayer world by hooking onto your internal server instance, if it doesnt work and crashes send your crash logs and i would be more then happy to help fix it for you.

**Comment by Pranavk246** [comment]
So you mean I just install the Mod and BFAPI into my mods folder in my Minecraft directory?

**Comment by BradBot1** [comment]
Yup

**Comment by Pranavk246** [comment]
Hey, I have tried what you suggested but I cant seem to get it working. I have installed it on my mods folder just like other mods but when I try to run Minecraft and try and sit it does not seem to work. I also noticed that this mod isnt detected in my ModMenu plugin. Something doesnt look right, any ideas?

**Comment by BradBot1** [comment]
Please update to 1.6.3 for client 'support' (i forgot to switch from server side only lmao)

**Comment by Pranavk246** [comment]
Still cant get it working buddy! :(

Nothing happens when I right click, with or without items

**Comment by BradBot1** [comment]
I just looked at logs and what not and it seems not even configs are being generated, so I do not think anything is loaded. seems i was wrong sorry.

**Comment by Pranavk246** [comment]
Hey so does it mean its not compatible right now? Should I wait for it to be compatible? Please let me know! :)
