### ISSUE TITLE
v1.6.3 doesn't work on client

### ISSUE THREAD

**Issue by hexakon** [BradBot1/FabricSit#12]
The mod does not appear to be loaded by the client and doesn't run in singleplayer/LAN worlds (integrated servers). I'm playing on fabric 1.17.1. "fabricsit" appears in the game log output in the list of mods being loaded, and then never again. There are no config files generated for fabricsit or bfapi. Everything still works in a typical server though

If this wasn't the intended effect of v1.6.3, then I propose it as a suggestion

**Comment by BradBot1** [comment]
This has been fixed in v1.6.4

The bug was that I forgot to change the environment

Sorry about that and thanks for the report!
