### ISSUE TITLE
1.18

### ISSUE THREAD

**Issue by EysseW** [BradBot1/FabricSit#18]
Any plans for 1.18?

**Comment by BradBot1** [comment]
There are, I'm working on upgrading the api to make it better first though.

**Comment by BradBot1** [comment]
That took longer than expected but it should be done now! There was some merging conflicts (i forgot to merge before updating ;/) so if you find a bug feel free to open another issue.

**Comment by EysseW** [comment]
Thanks!

**Comment by yuanjv** [comment]
...

**Comment by BradBot1** [comment]
> ...

... ?

**Comment by t0mtee** [comment]
> > ...
> 
> ... ?

i think they're referencing the fact that you've only updated the mod on curseforge. it would be nice to see an updated version on github and modrinth

**Comment by BradBot1** [comment]
Modrinth gets updates before curseforge and github is too much hassle to post versions on
