### ISSUE TITLE
Chair not deleted

### ISSUE THREAD

**Issue by florentin-leclercq** [BradBot1/FabricSit#3]
Hi there, I found that when teleporting (with an enderpearl or a command) (the command part isn't tested) or when dying (untested) the chair isn't deleted.
Sorry for the untested parts, but last time I read your code it wasn't implemented.

Thanks ;)

**Comment by BradBot1** [comment]
You were 100% correct, I have fixed the death issue and the teleportation issue. Thanks for the report.
