### ISSUE TITLE
/sit fails to remove armorstand, /sit works while seated

### ISSUE THREAD

**Issue by sampfalcon** [BradBot1/FabricSit#4]
When the player uses the /sit command to sit down on a non-slab/ non-stair block, the invisible armorstand is not deleted after they get off. I think this issue may be related to [Issue#3](https://github.com/BradBot1/FabricSit/issues/3). Also, the /sit command does not check if the player is already sitting, so the player can /sit multiple times, resulting in them sinking into the ground. This can be used to clip into places the player is not supposed to be. I like this mod, however, and it fulfills the need I had, just these issues need to be fixed.

**Comment by BradBot1** [comment]
I have patched the /sit spam however I cannot reproduce the issue where the armour stand is left behind.
Do you mind giving more details on how that occurs and then opening another issue with it? (or you can reopen this one)

**Comment by sampfalcon** [comment]
I just tried it out, the armorstand was left behind only when you do /sit again, so with the patch it shouldn't be an issue.

**Comment by sampfalcon** [comment]
Thank you!

**Comment by BradBot1** [comment]
Alright good to hear, ill publish the patch after I fix #3
