### ISSUE TITLE
Players gets kicked when joining server

### ISSUE THREAD

**Issue by Soham52** [BradBot1/FabricSit#9]
Whenever two or more players join the server, they get disconnected.
Sometimes the server even crashes
Log:
https://cdn.discordapp.com/attachments/848608690776834068/876809328919736350/2021-08-16-3.log

**Comment by BradBot1** [comment]
Is this on the right mod as I simply cannot reproduce this issue?

**Comment by Soham52** [comment]
Yes, I was testing manually with each mod and as soon as i uninstalled fabricsit and bfapi, everything was fine.
This maybe a incompatibility with any other mod also.
Here is the list of my mods:
https://media.discordapp.net/attachments/848608690776834068/877056996094914580/unknown.png

**Comment by Soham52** [comment]
Also, if you want i can share my server with you for testing

**Comment by BradBot1** [comment]
if you could send a copy of all those jars I would be happy to do some more investigation

**Comment by Soham52** [comment]
Here: 
https://drive.google.com/file/d/10vJvnT8IGiAT5r6vqHD9C3LjTK7r4E9H/view?usp=sharing

**Comment by BradBot1** [comment]
You are on an outdated version of bfapi: update and see if it persists

**Comment by BradBot1** [comment]
Just tested it, with your mods: there was no issue present

**Comment by Soham52** [comment]
Ok that works, but i think you should update both of your mod on all the platforms because at first I thought that I was using the latest version of bfapi because i was only looking on GitHub

**Comment by Soham52** [comment]
But anyway thanks for helping

**Comment by BradBot1** [comment]
Okay then, thanks for the issue.
